### PR TITLE
Update to 1.0.0 and include Neo4j Graph Algorithms library

### PR DESCRIPTION
**Pull request by szarnyasg**
**Not ready to merge.**

* [x] BFS - works using an unweighted SSSP approach (might be suboptimal)
* [ ] CDLP - see https://github.com/ldbc/ldbc_graphalytics/issues/167
* [ ] LCC - algo lib only supports undirected, see https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/844
* [ ] PR - ~algo lib only supports directed, see https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/845~ algo lib produces unnormalized PageRank, contacted @mneedham about this
* [x] SSSP - see issue https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/599
* [x] WCC

@thegeman I just wanted to let you now that I am working on updating this to Graphalytics 0.9, Neo4j 3.3.x, and also work to benchmark Neo4j's [Graph Algorithms library](https://neo4j-contrib.github.io/neo4j-graph-algorithms/).

### CODE REVIEW

**Comment by thegeman** [comment]
Thanks for picking this up, @szarnyasg!

We dropped support for Neo4j a while back due to the lack of dedicated analytics support, lack of expertise in our team to optimize our implementation, and lack of time/people at Neo to provide their own implementation. I haven't had a chance to try out their new algorithms library, so I'm curious to see how it performs.

**Comment by szarnyasg** [comment]
@thegeman I noticed that there are 7 graph algorithms in Graphalytics 0.9.0. Is the forest fire model algorithm relevant, should it be included in the implementation?

**Comment by thegeman** [comment]
The forest fire model algorithm is no longer part of the benchmark, so you can skip it. We left it in the core code to avoid breaking builds and to allow others to implement the algorithm anyway for custom benchmarking (using our validater to ensure that implementations are comparable). We intend to add more of such optional algorithms in the future.

For now, there is a comment at the definition of `Algorithm.FFM` stating that it was previously included in the benchmark. Should we mark it as `@Deprecated`? Or maybe update the Javadoc/implementation guide to stress which algorithms are mandatory?

**Comment by szarnyasg** [comment]
Thanks for clarifying this. I think deprecating it would be a nice way of signalling that implementation is no longer mandatory in a given version of Graphalytics. But it’s not hugely important for me.

**Comment by mihaic** [comment]
I am not sure deprecation is the right approach here. I think instead we should express the standard benchmark in the API somehow. Then, we could even add new algorithms for custom benchmarking.

**Comment by szarnyasg** [comment]
I ran into an issue with SSSP, but the folks developing the Graph Algorithms library were very helpful and quick. Using the implementation on https://github.com/neo4j-contrib/neo4j-graph-algorithms/pull/600 resolves the issue.

image

Extrapolating from the previous releases, I believe the next stable version of the graph algorithm library will be released late Spring/early Summer.

**Comment by szarnyasg** [comment]
@amusaafir @thegeman I'd propose to git merge with what we have now - BFS, SSSP and WCC already work correctly, along with undirected LCC. The embedded version of Neo4j supports all algorithms.

Do you folks agree to merge this? (Currently, I don't have the rights to perform the operation.)

**Pull request merged**
